# Generated by Django 4.2.8 on 2023-12-28 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Box', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='length',
            new_name='width',
        ),
        migrations.AlterField(
            model_name='box',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
