# Generated by Django 4.2.8 on 2023-12-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0002_rename_length_box_width_alter_box_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='breadth',
            new_name='length',
        ),
    ]
